apiVersion: apps/v1
kind: Deployment 
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: expiration
  template:
    metadata: 
      labels: 
        app: expiration
    spec:
      containers:
        - name: expiration
          image: mbraer/expiration   #us.gcr.io/thecrescenttheater/expiration
          env: 
            - name: NATS_URL
              value: 'http://nats-srv:4222' 
            - name: NATS_CLUSTER_ID
              value: ticketing 
            - name: NATS_CLIENT_ID
              valueFrom: # take pod name and use as client id
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expiration-redis-srv
              