apiVersion: apps/v1
kind: Deployment 
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: tickets
  template:
    metadata: 
      labels: 
        app: tickets
    spec:
      containers:
        - name: tickets
          image: mbraer/tickets   #us.gcr.io/thecrescenttheater/tickets
          env: 
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets' 
            - name: NATS_URL
              value: 'http://nats-srv:4222' 
            - name: NATS_CLUSTER_ID
              value: univenue 
            - name: NATS_CLIENT_ID
              valueFrom: # take pod name and use as client id
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
              