name: deploy-manifests

on: 
  push: 
    branches:
      - main
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2 #set of commands to setup doctl in github container
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save univenue
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
   
