name: tests-orders

on:
  pull_request:
    paths: #run test only if changes are made to orders service
        - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
