name: tests-tickets

on:
  pull_request:
    paths: #run test only if changes are made to tickets service
        - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd tickets && npm install && npm run test:ci
